// <auto-generated />
using System;
using BibliotecaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BibliotecaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaApi.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("NACIONALIDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id")
                        .HasName("PK_AUTOR");

                    b.ToTable("TB_AUTOR", (string)null);
                });

            modelBuilder.Entity("BibliotecaApi.Models.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_DEVOLUCAO");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_EMPRESTIMO");

                    b.Property<DateTime>("DataPrevistaDevolucao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PREVISTA_DEVOLUCAO");

                    b.Property<string>("EmailLeitor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL_LEITOR");

                    b.Property<int>("LivroId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LIVRO_ID");

                    b.Property<string>("NomeLeitor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_LEITOR");

                    b.HasKey("Id")
                        .HasName("PK_EMPRESTIMO");

                    b.HasIndex("LivroId")
                        .HasDatabaseName("IX_EMPRESTIMO_LIVRO");

                    b.ToTable("TB_EMPRESTIMO", (string)null);
                });

            modelBuilder.Entity("BibliotecaApi.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoPublicacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANO_PUBLICACAO");

                    b.Property<int>("AutorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AUTOR_ID");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DISPONIVEL");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)")
                        .HasColumnName("ISBN");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id")
                        .HasName("PK_LIVRO");

                    b.HasIndex("AutorId")
                        .HasDatabaseName("IX_LIVRO_AUTOR");

                    b.HasIndex("Isbn")
                        .IsUnique()
                        .HasDatabaseName("UX_LIVRO_ISBN");

                    b.ToTable("TB_LIVRO", (string)null);
                });

            modelBuilder.Entity("BibliotecaApi.Models.Emprestimo", b =>
                {
                    b.HasOne("BibliotecaApi.Models.Livro", "Livro")
                        .WithMany("Emprestimos")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EMPRESTIMO_LIVRO");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("BibliotecaApi.Models.Livro", b =>
                {
                    b.HasOne("BibliotecaApi.Models.Autor", "Autor")
                        .WithMany("Livros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LIVRO_AUTOR");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("BibliotecaApi.Models.Autor", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("BibliotecaApi.Models.Livro", b =>
                {
                    b.Navigation("Emprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
